-- Internal Users Table
CREATE TABLE IF NOT EXISTS internal_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    department VARCHAR(100),
    is_designated_recipient BOOLEAN DEFAULT TRUE
    );

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER DEFAULT 0,              -- Added for Optimistic Locking
    mobile_user_name VARCHAR(255)  NOT NULL, -- Added this column
    recipient VARCHAR(255) NOT NULL, -- allows email for EMAIL, deviceToken for PUSH and Mobile Number for SMS
    content VARCHAR(MAX) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

--  Indexes
CREATE INDEX IF NOT EXISTS idx_notifications_status_schedule ON notifications (status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_internal_users_designated ON internal_users (is_designated_recipient);